const button = document.getElementById("button");
const h2 = document.getElementById("h2");
const array = [
  "Wisdom is the reward you get for a lifetime of listening <br> when you'd have preferred to talk <br> &copy; Doug Larson",
  "We need to find the courage to say no to the things and people <br> that are not serving us if we want to rediscover ourselves <br> and live our lives with authenticity. <br> &copy; Barbara de Angelis",
  "I know of nothing more valuable, when it comes to the <br> all-important virtue of authenticity, than simply being who you are. <br> &copy; Charles R. Swindoll",
  "Yes, in all my research, the greatest leaders looked inward <br> and were able to tell a good story with authenticity and passion <br> &copy; Deepak Chopra",
  "Authentic brands don't emerge from marketing cubicles or advertising agencies. <br> They emanate from everything the company does. <br> &copy; Howard Schultz",
  "Talent wins games, but teamwork and intelligence wins championships. <br> &copy; Michael Jordan",
  "Teamwork is the ability to work together toward a common vision. <br> The ability to direct individual accomplishments toward organizational objectives. <br> It is the fuel that allows common people to attain uncommon results <br> &copy; Andrew Carnegie",
  "Alone we can do so little, together we can do so much. <br> &copy; Helen Keller",
  "Life is 10% what happens to me and 90% how I react. <br> &copy; John Maxwell",
  "It is not the strongest or the most intelligent who will <br> survive but those who can best manage change <br> &copy; Charles Darwin",
  "Adaptability is not imitation. <br> It means power of resistance and assimilation. <br> &copy; Mahatma Gandhi",
  "Fall seven times and stand up eight. <br> &copy; Japanese Proverb",
  "There is no end. There is no beginning. <br> There is only the passion of life. There is no end. <br> There is no beginning. There is only the passion of life. <br> &copy; Federico Fellini",
  "Surprise yourself every day with your own courage. <br> &copy; Denholm Elliott",
  "Never tell people how to do things. <br> Tell them what to do and they will surprise you with their ingenuity. <br> &copy; George S. Patton",
  "Simplicity and repose are the qualities <br> that measure the true value of any work of art. <br> &copy; Frank Lloyd Wright",
  "Free yourself from the complexities of your life! <br> A life of simplicity and happiness awaits you. <br> &copy; Steve Maraboli",
  "Nature is pleased with simplicity. <br> And nature is no dummy. <br> &copy; Isaac Newton",
  "I work very hard, and I play very hard. I'm grateful for life. <br> And I live it I believe life loves the liver of it. I live it. <br> &copy; Maya Angelou",
  "When you are grateful when you can see what you have <br> you unlock blessings to flow in your life. <br> &copy; Suze Orman",
  "Truth is a deep kindness that teaches us to be content in our <br>  everyday life and share with the people the same happiness. <br> &copy; Khalil Gibran",
  "Treat everyone with respect and kindness. <br> Period. No exceptions. <br> &copy; Kiana Tom",
  "Be kind, for everyone you meet is fighting a harder battle. <br> &copy; Plato",
  "Kindness is a language which the deaf <br> can hear and the blind can see. <br> &copy; Mark Twain",
  "The smallest act of kindness is worth <br> more than the greatest intention. <br> &copy; Kahlil Gibran",
  "Never lose a chance of saying a kind word. <br> &copy; William Makepeace Thackeray ",
  "Our kindness may be the most persuasive  <br> argument for that which we believe. <br> &copy; Gordon B. Hinckley",
  "It seems to me that no matter what religion you subscribe to, <br> acts of kindness are the stepping stones to making the world <br>  a better place because we become better people in it. <br> &copy; Jodi Picoult",
  "Never look down on anybody unless you're helping them up. <br> &copy; Jesse Jackson",
  "Pride makes us artificial and humility makes us real. <br> &copy; Thomas Merton",
  "The greatest friend of truth is Time, <br> her greatest  enemy is Prejudice, <br> and her constant companion is Humility. <br> &copy; Charles Caleb Colton",
  "One cannot be humble and aware of oneself at the same time. <br> &copy; Madeleine L'Engle,",
  "Give, but give until it hurts. <br> &copy; Mother Teresa",
  "As we work to create light for others, <br> we naturally light our own way. <br> &copy; Mary Anne Radmacher",
  "Until we can receive with an open heart, <br> we're never really giving with an open heart. <br> When we attach judgment to receiving help, we knowingly <br> or unknowingly attach judgment to giving help. <br> Bren Brown",
  "Don't wait for other people to be <br>  loving, giving, compassionate, grateful, forgiving, generous, or friendly... <br> lead the way! <br> &copy; Steve Maraboli",
  "What we spend, we lose. What we keep will be left for others. <br> What we give away will be ours forever. <br> &copy; David McGee",
  "There is a very real relationship, both quantitatively and qualitatively, <br> between what you contribute and what you get out of this world. <br> &copy; Oscar Hammerstein II",
  "Just like downing a powerful caffeine drink, <br>\"reaching out to others\" pays that big \"life energizer dividend!\" <br> &copy; Wes Adamson",
  "Every sunrise is an invitation for us to arise <br>  and brighten someone's day. <br> &copy; Richelle E. Goodrich",
  "Energy and persistence conquer all things. <br> &copy; Benjamin Franklin",
  "Success is almost totally dependent upon drive and persistence. <br> The extra energy required to make another effort <br> or try another approach is the secret of winning. <br> &copy; Denis Waitley",
  "Never let your persistence and passion <br> turn into stubbornness and ignorance. <br> &copy; Anthony J. D'Angelo",
  "The difference between people who believe they have books inside of them <br>  and those who actually write books is sheer cussed persistence <br> the ability to make yourself work at your craft, every day the belief, <br> even in the face of obstacles, that you've got something worth saying. <br> &copy; Jennifer Weiner",
  "The best way out is always through. <br> &copy; Robert Frost",
  "No matter how much falls on us, we keep plowing ahead. <br> That's the only way to keep the roads clear. <br> &copy; Greg Kincaid",
  "It is during our darkest moments <br> that we must focus to see the light. <br> &copy; Aristotle Onassis",
  "Do you want to know who you are? Don't ask. Act! <br> Action will delineate and define you. <br> &copy; Thomas Jefferson",
  "The best way to predict the future is to invent it. <br> &copy; Alan Kay",
  "If not us, who? If not now, when? <br> &copy; Hillel the Elder",
  "Winners lose much more often than losers. <br> So if you keep losing but you're still trying, keep it up! <br> You're right on track. <br> &copy; Matthew Keith Groves",
  "When the need to succeed is as bad as <br> the need to breathe, then you'll be successful. <br> &copy; Eric Thomas",
  "If you want to test your memory, try to recall <br> what you were worrying about one year ago today. <br> &copy; E.Joseph Coffman",
  "What you do speaks so loudly that I cannot hear what you say. <br> &copy; Ralph Waldo Emerson",
  "In three words I can sum up everything <br> I've learned about life: it goes on. <br> &copy; Robert Frost",
  "Life is really simple, but we insist on making it complicated. <br> &copy; Confucius",
  "Only a life lived for others is a life worthwhile. <br> &copy; Albert Einstein",
  "Life is a succession of lessons which must be lived to be understood. <br> &copy; Helen Keller",
  "The price of anything is the amount of life you exchange for it. <br> &copy;Henry David Thoreau",
  "Love is not maximum emotion. Love is maximum commitment. <br> &copy; Sinclair B. Ferguson",
  "Although love is communicated in a number of ways, <br> our words often reflect the condition of our heart. <br> &copy; Jennifer Dion",
  "Keep love in your heart. A life without it is like <br> a sunless garden when the flowers are dead. <br> &copy; Oscar Wilde",
  "Sometimes the heart sees what is invisible to the eye. <br> &copy; H. Jackson Brown ",
  "I have decided to stick with love. <br>Hate is too great a burden to bear. <br> &copy; Martin Luther King",
  "Where there is love there is life. <br> &copy; Mahatma Gandhi",
  "Love yourself first and everything else falls into line. <br> You really have to love yourself to get anything done in this world. <br> &copy; Lucille Ball",
  "Love is a better teacher than duty. <br> &copy; Albert Einstein",
  "The best proof of love is trust. <br> &copy; Joyce Brothers",
  "Love is life. <br> And if you miss love, you miss life. <br> &copy; Leo Buscaglia",
  "Be the change that you wish to see in the world. <br> &copy; Mahatma Gandhi",
  "Never doubt that a small group of thoughtful, <br> committed, citizens can change the world. <br> Indeed, it is the only thing that ever has. <br> &copy; Margaret Mead",
  "Everyone thinks of changing the world, <br> but no one thinks of changing himself. <br> &copy; Leo Tolstoy",
  "Education is the most powerful weapon <br> which you can use to change the world. <br> &copy; Nelson Mandela",
  "No matter who you are, no matter what you did, <br>no matter where you've come from, you can always change, <br> become a better version of yourself. <br> &copy;  Madonna",
  "Change is the end result of all true learning. <br> &copy; Leo Buscaglia",
  "Forgiveness does not change the past, <br> but it does enlarge the future <br> &copy; Paul Boese",
  "Thank God I found the GOOD in goodbye <br> &copy; Beyonc Knowles",
  "The weak can never forgive. <br> Forgiveness is the attribute of the strong. <br> &copy; Mahatma Gandhi",
  "Always forgive your enemies nothing annoys them so much. <br> &copy; Oscar Wilde",
  "Forgiveness is the fragrance that the violet <br> sheds on the heel that has crushed it. <br> &copy; Mark Twain",
  "Yesterday is not ours to recover, but tomorrow is ours to win or lose. <br> &copy; Lyndon B. Johnson",
  "The love of family and the admiration of friends <br> is much more important than wealth and privilege. <br> Charles Kuralt",
  "Family is not an important thing. <br> It's everything. <br> &copy; Michael J. Fox",
  "You are born into your family <br> and your family is born into you. <br> No returns. No exchanges. <br> &copy; Elizabeth Berg",
  "That which does not kill us makes us stronger. <br> &copy; Friedrich Nietzsche",
  "We are only as strong as we are united, <br> as weak as we are divided. <br> &copy; J.K. Rowling",
  "A brave man acknowledges the strength of others. <br> &copy; Veronica Roth",
  "The world breaks every one and afterward <br> many are strong at the broken places. <br> &copy; Ernest Hemingway",
  "You feel your strength in the experience of pain. <br> &copy; Jim Morrison",
  "Its not always necessary to be strong, but to feel strong. <br> Jon Krakauer",
  "Mastering others is strength. <br> Mastering oneself makes you fearless. <br> &copy; Lao Tzu",
  "A leader is a dealer in hope. <br> &copy; Napoleon Bonaparte",
  "As we look ahead into the next century, <br> leaders will be those who empower others. <br> &copy; Bill Gates",
  "Innovation distinguishes between a leader and a follower. <br> &copy; Steve Jobs",
  "Create with the heart; <br> &copy;build with the mind. <br> &copy; Criss Jami",
  "The things you do for yourself are gone when you are gone, <br> but the things you do for others remain as your legacy. <br> &copy; Kalu Ndukwe Kalu",
  "The greatest use of life is to spend it <br> for something that will outlast it. <br> &copy; William James",
  "Success is not the key to happiness. <br>Happiness is the key to success. <br>If you love what you are doing, you'll be a success. <br> &copy; Albert Schweitzer",
  "You can complain because roses have thorns, <br> or you can be grateful that thorn bushes have roses. <br> &copy; Tom Wilson",
  "We can only be said to be alive in those moments <br> when our hearts are conscious of our treasures. <br> &copy; Thornton Wilder",
]

button.addEventListener("click", () => {

 h2.innerHTML = array[Math.floor(Math.random() * array.length)]
 

});



 